# Generated by Django 5.2.8 on 2025-11-25 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'catégories',
            },
        ),
        migrations.CreateModel(
            name='chansonnier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(max_length=50)),
                ('illustration_chansonnier', models.FileField(blank=True, null=True, upload_to='illustrations_chansonnier/')),
                ('type_papier', models.CharField(max_length=100)),
                ('prix_vente_unite', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'chansonnier',
            },
        ),
        migrations.CreateModel(
            name='chant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_chant', models.CharField(max_length=50)),
                ('auteur', models.CharField(max_length=100)),
                ('ville_origine', models.CharField(max_length=85)),
                ('illustration_chant', models.FileField(blank=True, null=True, upload_to='illustrations_chant/')),
                ('paroles', models.TextField()),
                ('paroles_pdf', models.FileField(blank=True, null=True, upload_to='paroles_pdf/')),
                ('description', models.CharField(max_length=255)),
                ('partition', models.FileField(blank=True, null=True, upload_to='partitions/')),
            ],
            options={
                'db_table': 'chant',
            },
        ),
        migrations.CreateModel(
            name='fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(max_length=100)),
                ('ville_fournisseur', models.CharField(max_length=85)),
                ('type_reliure', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'fournisseur',
            },
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('pseudo', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=85)),
                ('statut', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evenement', models.DateField()),
                ('lieu', models.CharField(max_length=50)),
                ('nom_evenement', models.CharField(max_length=50)),
                ('annonce_fil_actu', models.CharField(max_length=255)),
                ('histoire', models.TextField()),
            ],
            options={
                'db_table': 'evenement',
                'unique_together': {('date_evenement', 'lieu')},
            },
        ),
        migrations.CreateModel(
            name='piste_audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_mp3', models.FileField(upload_to='pistes_audio/')),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.chant')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.utilisateur')),
            ],
            options={
                'db_table': 'piste_audio',
            },
        ),
        migrations.CreateModel(
            name='commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.utilisateur')),
            ],
            options={
                'db_table': 'commande',
            },
        ),
        migrations.AddField(
            model_name='chant',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.utilisateur'),
        ),
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('chansonnier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.chansonnier')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.commande')),
            ],
            options={
                'db_table': 'commander',
                'unique_together': {('commande', 'chansonnier')},
            },
        ),
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chansonnier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.chansonnier')),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.chant')),
            ],
            options={
                'db_table': 'contenir',
                'unique_together': {('chant', 'chansonnier')},
            },
        ),
        migrations.CreateModel(
            name='Chanter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.chant')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.evenement')),
            ],
            options={
                'db_table': 'chanter',
                'unique_together': {('chant', 'evenement')},
            },
        ),
        migrations.CreateModel(
            name='fournir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fourniture', models.DateField()),
                ('chansonnier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.chansonnier')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.fournisseur')),
            ],
            options={
                'db_table': 'fournir',
                'unique_together': {('fournisseur', 'chansonnier', 'date_fourniture')},
            },
        ),
        migrations.CreateModel(
            name='Noter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rating', models.DateField()),
                ('piste_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.piste_audio')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.utilisateur')),
            ],
            options={
                'db_table': 'noter',
                'unique_together': {('utilisateur', 'piste_audio')},
            },
        ),
        migrations.CreateModel(
            name='favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_favori', models.DateField()),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.chant')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.utilisateur')),
            ],
            options={
                'db_table': 'favoris',
                'unique_together': {('utilisateur', 'chant')},
            },
        ),
        migrations.CreateModel(
            name='commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_comment', models.DateField()),
                ('texte', models.CharField(max_length=255)),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.chant')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.utilisateur')),
            ],
            options={
                'db_table': 'commentaire',
                'unique_together': {('utilisateur', 'chant', 'date_comment')},
            },
        ),
        migrations.CreateModel(
            name='appartenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.categories')),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.chant')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.utilisateur')),
            ],
            options={
                'db_table': 'appartenir',
                'unique_together': {('nom_categorie', 'chant', 'utilisateur')},
            },
        ),
    ]
