# Generated by Django 5.0.6 on 2025-12-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noter',
            name='date_rating',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='nom_role',
            field=models.CharField(db_index=True, default='user', max_length=50, unique=True),
        ),
    ]
