# Generated by Django 5.2.8 on 2025-12-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_role_utilisateur_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='role',
            new_name='nom_role',
        ),
    ]
