# Generated by Django 5.2.8 on 2025-12-06 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0004_rename_role_utilisateur_nom_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='nom_role',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gui.role'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='nom_role',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
