# Generated by Django 5.2.8 on 2025-12-06 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0005_remove_utilisateur_nom_role_utilisateur_role_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='categorie',
        ),
    ]
