# Generated by Django 5.2.8 on 2025-12-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_rename_categories_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='maitre_chant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
    ]
