# Generated by Django 5.2.8 on 2025-12-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0007_maitre_chant'),
    ]

    operations = [
        migrations.AddField(
            model_name='chant',
            name='categorie',
            field=models.ManyToManyField(blank=True, to='gui.categorie'),
        ),
    ]
