# Generated by Django 5.2.8 on 2025-12-07 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0008_chant_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='chansonnier_perso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(max_length=50)),
                ('illustration_chansonnier', models.FileField(blank=True, null=True, upload_to='illustrations_chansonnier/')),
                ('type_papier', models.CharField(max_length=100)),
                ('prix_vente_unite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_creation', models.DateField()),
            ],
            options={
                'db_table': 'chansonnier_perso',
            },
        ),
        migrations.CreateModel(
            name='template_chansonnier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_template', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('illustration_template', models.FileField(blank=True, null=True, upload_to='illustrations_template/')),
                ('type_papier', models.CharField(max_length=100)),
                ('prix_vente_unite', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'template_chansonnier',
            },
        ),
        migrations.AlterField(
            model_name='contenir',
            name='chant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.chant'),
        ),
        migrations.AlterUniqueTogether(
            name='commander',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='contenir',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='fournir',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commander',
            name='chansonnier_perso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.chansonnier_perso'),
        ),
        migrations.AddField(
            model_name='contenir',
            name='chansonnier_perso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.chansonnier_perso'),
        ),
        migrations.AddField(
            model_name='fournir',
            name='chansonnier_perso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.chansonnier_perso'),
        ),
        migrations.AlterUniqueTogether(
            name='commander',
            unique_together={('commande', 'chansonnier_perso')},
        ),
        migrations.AlterUniqueTogether(
            name='contenir',
            unique_together={('chant', 'chansonnier_perso')},
        ),
        migrations.AlterUniqueTogether(
            name='fournir',
            unique_together={('fournisseur', 'chansonnier_perso', 'date_fourniture')},
        ),
        migrations.RemoveField(
            model_name='commander',
            name='chansonnier',
        ),
        migrations.RemoveField(
            model_name='contenir',
            name='chansonnier',
        ),
        migrations.RemoveField(
            model_name='fournir',
            name='chansonnier',
        ),
        migrations.DeleteModel(
            name='chansonnier',
        ),
    ]
