# Generated by Django 5.2.8 on 2025-12-07 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0009_chansonnier_perso_template_chansonnier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commander',
            name='chansonnier_perso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.chansonnier_perso'),
        ),
        migrations.AlterField(
            model_name='contenir',
            name='chansonnier_perso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.chansonnier_perso'),
        ),
        migrations.AlterField(
            model_name='fournir',
            name='chansonnier_perso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gui.chansonnier_perso'),
            preserve_default=False,
        ),
    ]
