# Generated by Django 5.2.8 on 2025-12-07 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0010_alter_commander_chansonnier_perso_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contenir',
            new_name='contenir_chant_perso',
        ),
        migrations.AddField(
            model_name='chansonnier_perso',
            name='nom_chansonnier_perso',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chansonnier_perso',
            name='template_chansonnier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.template_chansonnier'),
        ),
        migrations.AddField(
            model_name='chansonnier_perso',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.utilisateur'),
        ),
        migrations.AddField(
            model_name='commande',
            name='status',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template_chansonnier',
            name='couleur',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='contenir_chant_perso',
            table='contenir_chant_perso',
        ),
        migrations.CreateModel(
            name='contenir_chant_template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.chant')),
                ('template_chansonnier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.template_chansonnier')),
            ],
            options={
                'db_table': 'contenir_chant_template',
                'unique_together': {('chant', 'template_chansonnier')},
            },
        ),
    ]
