# Generated by Django 5.0.6 on 2025-12-08 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='chant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_chant', models.CharField(db_index=True, max_length=100)),
                ('auteur', models.CharField(blank=True, max_length=100, null=True)),
                ('ville_origine', models.CharField(blank=True, max_length=100, null=True)),
                ('paroles', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('illustration_chant', models.ImageField(blank=True, null=True, upload_to='illustrations/')),
                ('paroles_pdf', models.FileField(blank=True, null=True, upload_to='paroles_pdf/')),
                ('partition', models.FileField(blank=True, null=True, upload_to='partitions/')),
            ],
            options={
                'db_table': 'chant',
            },
        ),
        migrations.CreateModel(
            name='fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(max_length=100)),
                ('ville_fournisseur', models.CharField(max_length=85)),
                ('type_reliure', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'fournisseur',
            },
        ),
        migrations.CreateModel(
            name='maitre_chant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_role', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='template_chansonnier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_template', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('couleur', models.CharField(max_length=50)),
                ('illustration_template', models.FileField(blank=True, null=True, upload_to='illustrations_template/')),
                ('type_papier', models.CharField(max_length=100)),
                ('prix_vente_unite', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'template_chansonnier',
            },
        ),
        migrations.CreateModel(
            name='evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evenement', models.DateField()),
                ('lieu', models.CharField(max_length=50)),
                ('nom_evenement', models.CharField(max_length=50)),
                ('annonce_fil_actu', models.CharField(max_length=255)),
                ('histoire', models.TextField()),
            ],
            options={
                'db_table': 'evenement',
                'unique_together': {('date_evenement', 'lieu')},
            },
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('pseudo', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('ville', models.CharField(max_length=85)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gui.role')),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='piste_audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_mp3', models.FileField(upload_to='pistes_audio/')),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistes_audio', to='gui.chant')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.utilisateur')),
            ],
            options={
                'db_table': 'piste_audio',
            },
        ),
        migrations.CreateModel(
            name='commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.utilisateur')),
            ],
            options={
                'db_table': 'commande',
            },
        ),
        migrations.AddField(
            model_name='chant',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.utilisateur'),
        ),
        migrations.CreateModel(
            name='chansonnier_perso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_chansonnier_perso', models.CharField(max_length=100)),
                ('couleur', models.CharField(max_length=50)),
                ('illustration_chansonnier', models.FileField(blank=True, null=True, upload_to='illustrations_chansonnier/')),
                ('type_papier', models.CharField(max_length=100)),
                ('prix_vente_unite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_creation', models.DateField()),
                ('template_chansonnier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.template_chansonnier')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.utilisateur')),
            ],
            options={
                'db_table': 'chansonnier_perso',
            },
        ),
        migrations.CreateModel(
            name='contenir_chant_perso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chansonnier_perso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.chansonnier_perso')),
                ('chant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.chant')),
            ],
            options={
                'db_table': 'contenir_chant_perso',
                'unique_together': {('chant', 'chansonnier_perso')},
            },
        ),
        migrations.CreateModel(
            name='details_commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('chansonnier_perso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.chansonnier_perso')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.commande')),
            ],
            options={
                'db_table': 'details_commande',
                'unique_together': {('commande', 'chansonnier_perso')},
            },
        ),
        migrations.CreateModel(
            name='chanter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.chant')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.evenement')),
            ],
            options={
                'db_table': 'chanter',
                'unique_together': {('chant', 'evenement')},
            },
        ),
        migrations.CreateModel(
            name='fournir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fourniture', models.DateField()),
                ('chansonnier_perso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.chansonnier_perso')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.fournisseur')),
            ],
            options={
                'db_table': 'fournir',
                'unique_together': {('fournisseur', 'chansonnier_perso', 'date_fourniture')},
            },
        ),
        migrations.CreateModel(
            name='contenir_chant_template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.chant')),
                ('template_chansonnier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.template_chansonnier')),
            ],
            options={
                'db_table': 'contenir_chant_template',
                'unique_together': {('chant', 'template_chansonnier')},
            },
        ),
        migrations.CreateModel(
            name='noter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rating', models.DateField(auto_now_add=True)),
                ('valeur_note', models.PositiveSmallIntegerField()),
                ('piste_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.piste_audio')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.utilisateur')),
            ],
            options={
                'db_table': 'noter',
                'unique_together': {('utilisateur', 'piste_audio')},
            },
        ),
        migrations.CreateModel(
            name='favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_favori', models.DateField()),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.chant')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.utilisateur')),
            ],
            options={
                'db_table': 'favoris',
                'unique_together': {('utilisateur', 'chant')},
            },
        ),
        migrations.CreateModel(
            name='commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_comment', models.DateField()),
                ('texte', models.CharField(max_length=255)),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.chant')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.utilisateur')),
            ],
            options={
                'db_table': 'commentaire',
                'unique_together': {('utilisateur', 'chant', 'date_comment')},
            },
        ),
        migrations.CreateModel(
            name='appartenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartenances', to='gui.categorie')),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_associees', to='gui.chant')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.utilisateur')),
            ],
            options={
                'db_table': 'appartenir',
                'unique_together': {('categorie', 'chant', 'utilisateur')},
            },
        ),
    ]
