# Generated by Django 5.0.6 on 2025-12-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='type_reliure',
        ),
    ]
