# Generated by Django 5.0.6 on 2025-12-10 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentaire',
            unique_together={('utilisateur', 'chant')},
        ),
        migrations.RemoveField(
            model_name='chansonnier_perso',
            name='prix_vente_unite',
        ),
        migrations.RemoveField(
            model_name='template_chansonnier',
            name='prix_vente_unite',
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date_comment',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='favoris',
            name='date_favori',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='nom_role',
            field=models.CharField(db_index=True, default='user', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='demande_support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours'), ('RESOLU', 'Résolu')], default='NOUVEAU', max_length=20)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_support', to='gui.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='piece_jointe_support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='support/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='gui.demande_support')),
            ],
        ),
    ]
