# Generated by Django 5.0.6 on 2025-12-11 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_remove_fournisseur_type_reliure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande_chant',
            name='categories',
        ),
        migrations.AddField(
            model_name='demande_chant',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes_chant', to='gui.categorie'),
        ),
    ]
