# Generated by Django 5.0.6 on 2025-12-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_alter_noter_date_rating_alter_role_nom_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chansonnier_perso',
            name='prix_vente_unite',
        ),
        migrations.RemoveField(
            model_name='template_chansonnier',
            name='prix_vente_unite',
        ),
        migrations.AlterField(
            model_name='favoris',
            name='date_favori',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noter',
            name='date_rating',
            field=models.DateField(auto_now_add=True),
        ),
    ]
