# Generated by Django 5.0.6 on 2025-12-10 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_alter_commentaire_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='demande_chant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_chant', models.CharField(max_length=100)),
                ('auteur', models.CharField(blank=True, max_length=100, null=True)),
                ('ville_origine', models.CharField(blank=True, max_length=100, null=True)),
                ('paroles', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('illustration_chant', models.ImageField(blank=True, null=True, upload_to='illustrations/')),
                ('paroles_pdf', models.FileField(blank=True, null=True, upload_to='paroles_pdf/')),
                ('partition', models.FileField(blank=True, null=True, upload_to='partitions/')),
                ('categories', models.JSONField(blank=True, default=list)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('justification_refus', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_chants', to='gui.utilisateur')),
            ],
            options={
                'db_table': 'demande_chant',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='demande_chant_audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_mp3', models.FileField(upload_to='demandes_chants_audio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistes_audio', to='gui.demande_chant')),
            ],
            options={
                'db_table': 'demande_chant_audio',
            },
        ),
    ]
