# Generated by Django 5.0.6 on 2025-12-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_remove_chansonnier_perso_prix_vente_unite_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentaire',
            unique_together={('utilisateur', 'chant')},
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date_comment',
            field=models.DateField(auto_now_add=True),
        ),
    ]
