# Generated by Django 5.0.6 on 2025-12-10 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_demande_chant_demande_chant_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='demande_piste_audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_mp3', models.FileField(upload_to='demandes_pistes_audio/')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('justification_refus', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_pistes', to='gui.chant')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_pistes_audio', to='gui.utilisateur')),
            ],
            options={
                'db_table': 'demande_piste_audio',
                'ordering': ['-date_creation'],
            },
        ),
    ]
