# Generated by Django 5.0.6 on 2025-12-10 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0004_demande_piste_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='annonce_fil_actu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='demande_modification_chant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_chant', models.CharField(max_length=100)),
                ('auteur', models.CharField(blank=True, max_length=100, null=True)),
                ('ville_origine', models.CharField(blank=True, max_length=100, null=True)),
                ('paroles', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('illustration_chant', models.ImageField(blank=True, null=True, upload_to='illustrations/')),
                ('paroles_pdf', models.FileField(blank=True, null=True, upload_to='paroles_pdf/')),
                ('partition', models.FileField(blank=True, null=True, upload_to='partitions/')),
                ('categories', models.JSONField(blank=True, default=list)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('justification_refus', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_modifications', to='gui.chant')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_modifications_chant', to='gui.utilisateur')),
            ],
            options={
                'db_table': 'demande_modification_chant',
                'ordering': ['-date_creation'],
            },
        ),
    ]
